---

services:
  # Weaviate 向量資料庫
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
    - 8200:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    - weaviate_backups:/var/lib/weaviate/backups
    restart: unless-stopped
    healthcheck:          
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s       
      timeout: 5s
      retries: 3
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backups'
      CLUSTER_HOSTNAME: 'node1'

  # Weaviate 管理界面
  weaviate_console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "18081:80"
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080

  # 語音處理 API 服務
  unsaycret-api:
    build: .
    container_name: unsaycret-api
    ports:
      - "18000:8000"
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - WEAVIATE_SCHEME=http
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - LOG_LEVEL=INFO
      - MAX_WORKERS=3
      - GPU_ENABLED=false
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./stream_output:/app/stream_output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  weaviate_data:
  weaviate_backups: